language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
  - DB=mysql
before_install:
  - gem update --system 1.8.25 
  - gem install bundler
before_script:
  - cp config/database.yml.$DB config/database.yml
  - bundle exec rake db:create db:migrate
script: bundle exec ruby script/spec spec
